/* The following code was generated by JFlex 1.7.0 */

/* MiniJava Lexer usando Token diretamente */


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>mini_java.flex</tt>
 */
public class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\22\1\23\1\22\1\22\22\0\1\1\1\52\1\12"+
    "\3\0\1\50\1\10\1\64\1\65\1\24\1\55\1\62\1\56\1\63"+
    "\1\21\1\4\7\7\2\3\1\60\1\61\1\53\1\47\1\54\1\57"+
    "\1\0\6\17\21\15\1\16\2\15\1\70\1\11\1\71\1\0\1\2"+
    "\1\0\1\26\1\43\1\27\1\6\1\32\1\14\1\31\1\46\1\33"+
    "\1\20\1\30\1\40\1\34\1\13\1\35\1\25\1\20\1\36\1\41"+
    "\1\37\1\42\1\44\1\45\1\5\2\20\1\66\1\51\1\67\7\0"+
    "\1\23\u1fa2\0\1\23\1\23\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\4\1\3\2\1\2\3"+
    "\1\5\1\6\1\7\13\3\1\10\2\1\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\4\1\0"+
    "\1\31\4\0\1\32\5\3\1\2\1\0\7\3\1\33"+
    "\13\3\1\34\1\35\1\36\1\37\1\40\1\41\1\4"+
    "\1\42\1\3\1\43\2\3\1\44\1\0\6\3\1\45"+
    "\14\3\1\46\1\3\1\2\5\3\1\47\1\3\1\50"+
    "\1\3\1\51\1\52\4\3\1\53\2\3\1\54\3\3"+
    "\1\5\4\3\1\55\1\3\1\56\1\57\1\60\1\3"+
    "\1\61\2\3\1\62\1\63\1\64\1\3\1\65\1\3"+
    "\1\66\1\67\1\70";

  private static int [] zzUnpackAction() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\350\0\u0122\0\u015c\0\u0196"+
    "\0\u01d0\0\u020a\0\u0244\0\u027e\0\u02b8\0\72\0\u02f2\0\u032c"+
    "\0\u0366\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488\0\u04c2\0\u04fc"+
    "\0\u0536\0\u0570\0\u05aa\0\u05e4\0\u061e\0\u0658\0\u0692\0\72"+
    "\0\72\0\72\0\72\0\72\0\72\0\72\0\72\0\72"+
    "\0\72\0\72\0\72\0\72\0\u06cc\0\u0706\0\256\0\u0740"+
    "\0\u077a\0\u01d0\0\u07b4\0\72\0\u07ee\0\u0828\0\u0862\0\u089c"+
    "\0\u08d6\0\u0910\0\u094a\0\u0984\0\u09be\0\u09f8\0\u0a32\0\u0a6c"+
    "\0\u0aa6\0\u0ae0\0\256\0\u0b1a\0\u0b54\0\u0b8e\0\u0bc8\0\u0c02"+
    "\0\u0c3c\0\u0c76\0\u0cb0\0\u0cea\0\u0d24\0\u0d5e\0\72\0\72"+
    "\0\72\0\72\0\72\0\72\0\u0706\0\72\0\u0d98\0\256"+
    "\0\u0dd2\0\u0e0c\0\256\0\u0e46\0\u0e80\0\u0eba\0\u0ef4\0\u0f2e"+
    "\0\u0f68\0\u0fa2\0\256\0\u0fdc\0\u1016\0\u1050\0\u108a\0\u10c4"+
    "\0\u10fe\0\u1138\0\u1172\0\u11ac\0\u11e6\0\u1220\0\u125a\0\256"+
    "\0\u1294\0\72\0\u12ce\0\u1308\0\u1342\0\u137c\0\u13b6\0\256"+
    "\0\u13f0\0\256\0\u142a\0\256\0\256\0\u1464\0\u149e\0\u14d8"+
    "\0\u1512\0\256\0\u154c\0\u1586\0\256\0\u15c0\0\u15fa\0\u1634"+
    "\0\256\0\u166e\0\u16a8\0\u16e2\0\u171c\0\256\0\u1756\0\256"+
    "\0\256\0\256\0\u1790\0\256\0\u17ca\0\u1804\0\256\0\256"+
    "\0\256\0\u183e\0\256\0\u1878\0\256\0\256\0\256";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\4\1\7\1\5"+
    "\1\10\1\2\1\11\1\12\1\13\3\14\1\4\1\15"+
    "\1\3\1\0\1\16\1\17\1\4\1\20\2\4\1\21"+
    "\1\22\1\23\1\4\1\24\1\25\1\4\1\26\1\4"+
    "\1\27\1\30\1\31\1\4\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\73\0"+
    "\1\3\20\0\1\3\51\0\6\4\3\0\6\4\4\0"+
    "\22\4\26\0\2\5\2\0\1\5\66\0\1\55\1\56"+
    "\1\0\1\55\6\0\1\56\55\0\6\4\3\0\6\4"+
    "\4\0\10\4\1\57\11\4\23\0\10\60\1\0\1\61"+
    "\60\60\11\62\1\63\1\64\57\62\2\0\6\4\3\0"+
    "\6\4\4\0\1\4\1\65\3\4\1\66\7\4\1\67"+
    "\4\4\25\0\6\4\3\0\6\4\4\0\1\4\1\70"+
    "\6\4\1\71\11\4\25\0\1\4\5\14\3\0\6\14"+
    "\4\0\22\14\44\0\1\72\2\0\1\73\47\0\6\4"+
    "\3\0\6\4\4\0\1\4\1\74\13\4\1\75\4\4"+
    "\25\0\6\4\3\0\6\4\4\0\10\4\1\76\2\4"+
    "\1\77\6\4\25\0\3\4\1\100\2\4\3\0\6\4"+
    "\4\0\13\4\1\101\6\4\25\0\6\4\3\0\1\102"+
    "\1\103\4\4\4\0\7\4\1\104\12\4\25\0\6\4"+
    "\3\0\6\4\4\0\1\4\1\105\20\4\25\0\6\4"+
    "\3\0\6\4\4\0\5\4\1\106\14\4\25\0\6\4"+
    "\3\0\6\4\4\0\11\4\1\107\7\4\1\110\25\0"+
    "\6\4\3\0\6\4\4\0\12\4\1\111\2\4\1\112"+
    "\4\4\25\0\6\4\3\0\6\4\4\0\10\4\1\113"+
    "\1\114\10\4\25\0\6\4\3\0\6\4\4\0\10\4"+
    "\1\115\11\4\25\0\6\4\3\0\6\4\4\0\21\4"+
    "\1\116\72\0\1\117\72\0\1\120\72\0\1\121\67\0"+
    "\1\122\71\0\1\123\71\0\1\124\26\0\1\55\2\0"+
    "\1\55\65\0\2\125\1\0\2\125\4\0\1\125\2\0"+
    "\1\125\6\0\2\125\2\0\1\125\10\0\1\125\36\0"+
    "\1\126\71\0\5\60\21\0\2\60\3\0\1\60\36\0"+
    "\5\62\21\0\2\62\3\0\1\62\30\0\6\4\3\0"+
    "\6\4\4\0\12\4\1\127\7\4\25\0\6\4\3\0"+
    "\6\4\4\0\20\4\1\130\1\4\25\0\6\4\3\0"+
    "\6\4\4\0\13\4\1\131\6\4\25\0\6\4\3\0"+
    "\6\4\4\0\13\4\1\132\6\4\25\0\6\4\3\0"+
    "\6\4\4\0\11\4\1\133\10\4\23\0\22\72\2\0"+
    "\46\72\24\73\1\134\45\73\2\0\6\4\3\0\6\4"+
    "\4\0\2\4\1\135\17\4\25\0\6\4\3\0\6\4"+
    "\4\0\16\4\1\136\3\4\25\0\6\4\3\0\1\137"+
    "\5\4\4\0\22\4\25\0\6\4\3\0\6\4\4\0"+
    "\1\4\1\140\20\4\25\0\6\4\3\0\6\4\4\0"+
    "\12\4\1\141\7\4\25\0\6\4\3\0\6\4\4\0"+
    "\14\4\1\142\5\4\25\0\6\4\3\0\6\4\4\0"+
    "\12\4\1\143\7\4\25\0\6\4\3\0\6\4\4\0"+
    "\1\144\21\4\25\0\6\4\3\0\6\4\4\0\6\4"+
    "\1\145\13\4\25\0\6\4\3\0\6\4\4\0\12\4"+
    "\1\146\7\4\25\0\6\4\3\0\6\4\4\0\15\4"+
    "\1\147\4\4\25\0\6\4\3\0\6\4\4\0\6\4"+
    "\1\150\13\4\25\0\6\4\3\0\6\4\4\0\1\4"+
    "\1\151\20\4\25\0\6\4\3\0\6\4\4\0\1\152"+
    "\21\4\25\0\6\4\3\0\6\4\4\0\10\4\1\153"+
    "\11\4\25\0\6\4\3\0\6\4\4\0\5\4\1\154"+
    "\14\4\25\0\6\4\3\0\6\4\4\0\6\4\1\155"+
    "\13\4\25\0\6\4\3\0\6\4\4\0\6\4\1\156"+
    "\13\4\25\0\6\4\3\0\6\4\4\0\6\4\1\157"+
    "\13\4\25\0\6\4\3\0\6\4\4\0\13\4\1\160"+
    "\6\4\25\0\6\4\3\0\6\4\4\0\14\4\1\161"+
    "\5\4\23\0\21\73\1\162\2\73\1\134\45\73\2\0"+
    "\6\4\3\0\6\4\4\0\3\4\1\163\16\4\25\0"+
    "\6\4\3\0\6\4\4\0\13\4\1\164\6\4\25\0"+
    "\6\4\3\0\6\4\4\0\12\4\1\165\7\4\25\0"+
    "\6\4\3\0\6\4\4\0\14\4\1\166\5\4\25\0"+
    "\6\4\3\0\6\4\4\0\5\4\1\167\14\4\25\0"+
    "\6\4\3\0\6\4\4\0\5\4\1\170\14\4\25\0"+
    "\6\4\3\0\6\4\4\0\10\4\1\171\11\4\25\0"+
    "\6\4\3\0\1\172\5\4\4\0\22\4\25\0\6\4"+
    "\3\0\6\4\4\0\15\4\1\173\4\4\25\0\6\4"+
    "\3\0\6\4\4\0\5\4\1\174\14\4\25\0\6\4"+
    "\3\0\6\4\4\0\14\4\1\175\5\4\25\0\6\4"+
    "\3\0\6\4\4\0\12\4\1\176\7\4\25\0\6\4"+
    "\3\0\6\4\4\0\5\4\1\177\14\4\25\0\6\4"+
    "\3\0\6\4\4\0\13\4\1\200\6\4\25\0\6\4"+
    "\3\0\6\4\4\0\1\4\1\201\20\4\25\0\4\4"+
    "\1\202\1\4\3\0\6\4\4\0\22\4\25\0\6\4"+
    "\3\0\6\4\4\0\13\4\1\203\6\4\25\0\6\4"+
    "\3\0\6\4\4\0\17\4\1\204\2\4\25\0\6\4"+
    "\3\0\6\4\4\0\5\4\1\205\14\4\25\0\6\4"+
    "\3\0\6\4\4\0\1\4\1\206\20\4\25\0\6\4"+
    "\3\0\6\4\4\0\6\4\1\207\13\4\25\0\6\4"+
    "\3\0\6\4\4\0\6\4\1\210\13\4\25\0\6\4"+
    "\3\0\6\4\4\0\14\4\1\211\5\4\25\0\6\4"+
    "\3\0\1\212\5\4\4\0\22\4\25\0\6\4\3\0"+
    "\6\4\4\0\11\4\1\213\10\4\25\0\6\4\3\0"+
    "\6\4\4\0\11\4\1\214\10\4\25\0\6\4\3\0"+
    "\6\4\4\0\6\4\1\215\13\4\25\0\6\4\3\0"+
    "\6\4\4\0\11\4\1\216\10\4\25\0\6\4\3\0"+
    "\6\4\4\0\5\4\1\217\14\4\25\0\6\4\3\0"+
    "\6\4\4\0\3\4\1\220\16\4\25\0\6\4\3\0"+
    "\6\4\4\0\5\4\1\221\14\4\25\0\6\4\3\0"+
    "\6\4\4\0\5\4\1\222\14\4\25\0\6\4\3\0"+
    "\6\4\4\0\4\4\1\223\15\4\25\0\6\4\3\0"+
    "\6\4\4\0\2\4\1\224\17\4\25\0\6\4\3\0"+
    "\1\225\5\4\4\0\22\4\25\0\4\4\1\226\1\4"+
    "\3\0\6\4\4\0\22\4\25\0\6\4\3\0\6\4"+
    "\4\0\12\4\1\227\7\4\25\0\6\4\3\0\1\230"+
    "\5\4\4\0\22\4\25\0\6\4\3\0\6\4\4\0"+
    "\2\4\1\231\17\4\25\0\6\4\3\0\6\4\4\0"+
    "\1\4\1\232\20\4\25\0\6\4\3\0\6\4\4\0"+
    "\5\4\1\233\14\4\25\0\6\4\3\0\6\4\4\0"+
    "\15\4\1\234\4\4\25\0\6\4\3\0\6\4\4\0"+
    "\14\4\1\235\5\4\25\0\6\4\3\0\1\236\5\4"+
    "\4\0\22\4\25\0\6\4\3\0\6\4\4\0\5\4"+
    "\1\237\14\4\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6322];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\13\1\1\11\21\1\15\11\1\1\1\0"+
    "\1\1\4\0\1\11\6\1\1\0\23\1\6\11\1\1"+
    "\1\11\5\1\1\0\25\1\1\11\55\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 182) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return new Token(Symbol.EOF, yyline+1, yycolumn+1);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.err.println("Caractere inválido: " + yytext() +
                       " na linha " + (yyline+1) +
                       ", coluna " + (yycolumn+1)); 
    return new Token(Symbol.NULL, yyline+1, yycolumn+1);
            } 
            // fall through
          case 57: break;
          case 2: 
            { /* ignora */
            } 
            // fall through
          case 58: break;
          case 3: 
            { return new Token(Symbol.ID, yytext(), yyline+1, yycolumn+1);
            } 
            // fall through
          case 59: break;
          case 4: 
            { return new Token(Symbol.INTEGER, Integer.decode(yytext()), yyline+1, yycolumn+1);
            } 
            // fall through
          case 60: break;
          case 5: 
            { return new Token(Symbol.CLASS, yyline+1, yycolumn+1);
            } 
            // fall through
          case 61: break;
          case 6: 
            { return new Token(Symbol.DIVISAO, yyline+1, yycolumn+1);
            } 
            // fall through
          case 62: break;
          case 7: 
            { return new Token(Symbol.MULTIPLICACAO, yyline+1, yycolumn+1);
            } 
            // fall through
          case 63: break;
          case 8: 
            { return new Token(Symbol.ATRIBUICAO, yyline+1, yycolumn+1);
            } 
            // fall through
          case 64: break;
          case 9: 
            { return new Token(Symbol.NAO, yyline+1, yycolumn+1);
            } 
            // fall through
          case 65: break;
          case 10: 
            { return new Token(Symbol.MENOR, yyline+1, yycolumn+1);
            } 
            // fall through
          case 66: break;
          case 11: 
            { return new Token(Symbol.MAIOR, yyline+1, yycolumn+1);
            } 
            // fall through
          case 67: break;
          case 12: 
            { return new Token(Symbol.ADICAO, yyline+1, yycolumn+1);
            } 
            // fall through
          case 68: break;
          case 13: 
            { return new Token(Symbol.SUBTRACAO, yyline+1, yycolumn+1);
            } 
            // fall through
          case 69: break;
          case 14: 
            { return new Token(Symbol.INTERROGACAO, yyline+1, yycolumn+1);
            } 
            // fall through
          case 70: break;
          case 15: 
            { return new Token(Symbol.DOIS_PONTOS, yyline+1, yycolumn+1);
            } 
            // fall through
          case 71: break;
          case 16: 
            { return new Token(Symbol.PONTO_VIRGULA, yyline+1, yycolumn+1);
            } 
            // fall through
          case 72: break;
          case 17: 
            { return new Token(Symbol.VIRGULA, yyline+1, yycolumn+1);
            } 
            // fall through
          case 73: break;
          case 18: 
            { return new Token(Symbol.PONTO, yyline+1, yycolumn+1);
            } 
            // fall through
          case 74: break;
          case 19: 
            { return new Token(Symbol.ABRE_PARENTESES, yyline+1, yycolumn+1);
            } 
            // fall through
          case 75: break;
          case 20: 
            { return new Token(Symbol.FECHA_PARENTESES, yyline+1, yycolumn+1);
            } 
            // fall through
          case 76: break;
          case 21: 
            { return new Token(Symbol.ABRE_CHAVES, yyline+1, yycolumn+1);
            } 
            // fall through
          case 77: break;
          case 22: 
            { return new Token(Symbol.FECHA_CHAVES, yyline+1, yycolumn+1);
            } 
            // fall through
          case 78: break;
          case 23: 
            { return new Token(Symbol.ABRE_COLCHETES, yyline+1, yycolumn+1);
            } 
            // fall through
          case 79: break;
          case 24: 
            { return new Token(Symbol.FECHA_COLCHETES, yyline+1, yycolumn+1);
            } 
            // fall through
          case 80: break;
          case 25: 
            { return new Token(Symbol.DO, yyline+1, yycolumn+1);
            } 
            // fall through
          case 81: break;
          case 26: 
            { return new Token(Symbol.STRING, yytext().substring(1, yytext().length()-1), yyline+1, yycolumn+1);
            } 
            // fall through
          case 82: break;
          case 27: 
            { return new Token(Symbol.IF, yyline+1, yycolumn+1);
            } 
            // fall through
          case 83: break;
          case 28: 
            { return new Token(Symbol.IGUAL, yyline+1, yycolumn+1);
            } 
            // fall through
          case 84: break;
          case 29: 
            { return new Token(Symbol.E, yyline+1, yycolumn+1);
            } 
            // fall through
          case 85: break;
          case 30: 
            { return new Token(Symbol.OU, yyline+1, yycolumn+1);
            } 
            // fall through
          case 86: break;
          case 31: 
            { return new Token(Symbol.DIFERENTE, yyline+1, yycolumn+1);
            } 
            // fall through
          case 87: break;
          case 32: 
            { return new Token(Symbol.MENOR_OU_IGUAL, yyline+1, yycolumn+1);
            } 
            // fall through
          case 88: break;
          case 33: 
            { return new Token(Symbol.MAIOR_OU_IGUAL, yyline+1, yycolumn+1);
            } 
            // fall through
          case 89: break;
          case 34: 
            { return new Token(Symbol.CHAR, yytext().charAt(1), yyline+1, yycolumn+1);
            } 
            // fall through
          case 90: break;
          case 35: 
            { return new Token(Symbol.NEW, yyline+1, yycolumn+1);
            } 
            // fall through
          case 91: break;
          case 36: 
            { return new Token(Symbol.FOR, yyline+1, yycolumn+1);
            } 
            // fall through
          case 92: break;
          case 37: 
            { return new Token(Symbol.INT, yyline+1, yycolumn+1);
            } 
            // fall through
          case 93: break;
          case 38: 
            { return new Token(Symbol.NULL, yyline+1, yycolumn+1);
            } 
            // fall through
          case 94: break;
          case 39: 
            { return new Token(Symbol.ELSE, yyline+1, yycolumn+1);
            } 
            // fall through
          case 95: break;
          case 40: 
            { return new Token(Symbol.MAIN, yyline+1, yycolumn+1);
            } 
            // fall through
          case 96: break;
          case 41: 
            { return new Token(Symbol.TRUE, true, yyline+1, yycolumn+1);
            } 
            // fall through
          case 97: break;
          case 42: 
            { return new Token(Symbol.THIS, yyline+1, yycolumn+1);
            } 
            // fall through
          case 98: break;
          case 43: 
            { return new Token(Symbol.VOID, yyline+1, yycolumn+1);
            } 
            // fall through
          case 99: break;
          case 44: 
            { return new Token(Symbol.FALSE, false, yyline+1, yycolumn+1);
            } 
            // fall through
          case 100: break;
          case 45: 
            { return new Token(Symbol.SUPER, yyline+1, yycolumn+1);
            } 
            // fall through
          case 101: break;
          case 46: 
            { return new Token(Symbol.BREAK, yyline+1, yycolumn+1);
            } 
            // fall through
          case 102: break;
          case 47: 
            { return new Token(Symbol.WHILE, yyline+1, yycolumn+1);
            } 
            // fall through
          case 103: break;
          case 48: 
            { return new Token(Symbol.NATIVE, yyline+1, yycolumn+1);
            } 
            // fall through
          case 104: break;
          case 49: 
            { return new Token(Symbol.PUBLIC, yyline+1, yycolumn+1);
            } 
            // fall through
          case 105: break;
          case 50: 
            { return new Token(Symbol.IMPORT, yyline+1, yycolumn+1);
            } 
            // fall through
          case 106: break;
          case 51: 
            { return new Token(Symbol.RETURN, yyline+1, yycolumn+1);
            } 
            // fall through
          case 107: break;
          case 52: 
            { return new Token(Symbol.STATIC, yyline+1, yycolumn+1);
            } 
            // fall through
          case 108: break;
          case 53: 
            { return new Token(Symbol.PACKAGE, yyline+1, yycolumn+1);
            } 
            // fall through
          case 109: break;
          case 54: 
            { return new Token(Symbol.EXTENDS, yyline+1, yycolumn+1);
            } 
            // fall through
          case 110: break;
          case 55: 
            { return new Token(Symbol.BOOLEAN, yyline+1, yycolumn+1);
            } 
            // fall through
          case 111: break;
          case 56: 
            { return new Token(Symbol.CONTINUE, yyline+1, yycolumn+1);
            } 
            // fall through
          case 112: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
